#!/usr/bin/env python3

#Randomized text string and pattern to find
text = "AGTGGATCAGTGGATCCCTCGACTGTGGATCTGTGGATCCCTAGTCCAACCTTGTGGATCATATGTGGATCGTATAGTGGATCTTAGTGGATCGTGGATCGTGGATCGAAGGTGGATCTTGGTGGATCAACGTGGATCGAATGTGGATCACGTGGATCGTGGATCGTTGTGGATCACGTGGATCTAGGAGTGGATCGGTGGATCGTGGATCGTGGATCAGCTGTGGATCCTAGTGGATCTGCCCGTGGATCGTGGATCCTCGCTGTGGATCACGAATGGCGGTGGATCTGTGGATCCGAATATCATCTCGTGGATCAGTGGATCCTAGGCGGTGGATCAGTGGATCCACAAGTGGATCTTGTGGATCTAAGGTGGATCGGTGGATCGTGGATCTACGTGGATCGTGGATCAGACATGTAACGTCGTGGATCAGCGTGGATCTTCCTCCCATAGTGGATCCGGGTGGGTGGATCCGTGGATCTTTTTAGTGGATCCCAGTGGATCTGTGGATCTCGCCCTCCTGTGGATCGATGCTGTGGATCCCAATGTGGATCGTGGATCACTGGTGGATCTGTGGATCGTGGATCCTTGTGGATCAGTGGATCCGTGGATCCGTCGTGGATCAATGAACTGTGGATCTTTAGTAAAGTGGATCCAGTGGATCGGTGGATCAGGTGGATCTTGTGGATCGTTGCAAGTGGATCGTGGATCCCGTGGATCGTGGATCGTGGATCGTGGATCTTTCCGTGGATCCGCTCACATCAGGTGGATCAGGCGTGGATCGCACGGTGGATCATTGTGGATCGTGGATCGTGTGGATCGGTGTGGATCTTAGTGGATCTTGTGGATCGGTGGGTGGATCACTAACATTCTGTGGATCGTGGATCTCGAGTGGATCGTGGATCACGTGGATCATTCCCCAGTGGATCCGTGGATCCGGAATGTGGATCGCACGGTGGATCCCGGGGTGGATCGACTGTGGATCGGAGTGGATCGTGGATCGTGGATCGTAGGGTGGATCTAGGTGGATCAGTGGATCTGTGTGGATCGTGGATCAACGTGGATC"
pattern = "GTGGATCGT"

#Function to find the pattern count
def patternFind(text, pattern):
    count = 0

    #Increases count for every instance of the pattern found
    for i in range(len(text) - len(pattern) + 1):
        if text[i:i+len(pattern)] == pattern:
            count = count+1
    return count

#prints out the found number of patterns
print (patternFind(text, pattern))
